#cloud-config

byobu_by_default: system

timezone: America/Chicago

growpart:
      mode: auto
      devices: "/"
resize_rootfs: true

packages:
      - terraform
      - terraform-ls
      - docker-engine
      - tailscale
      - node
      - npm
      - nvim 
package_update: true
package_upgrade: true
package_reboot_if_required: true

runcmd:
      - [truescale up]
